### ISSUE TITLE
Build profile with appDir and paths config results in source file overwriting

### ISSUE THREAD

**Issue by jrburke** [jrburke/r.js#108]
Reported against 1.0.6 in this thread:

http://groups.google.com/group/requirejs/browse_thread/thread/b97bc643c9dc9355

Basically, the paths config gets absolute values under the source area, and when appDir is in play, those paths were not updated to be under the final dirBaseUrl.

This caused overwriting of source files, and not including expected files in the built area's build targets.

**Comment by nitinsurana** [comment]
I'm using r.js 2.1.15 & having the same issue as mentioned in the google-groups thread. I don't have paths in my build-config.js file though.

The configuration looks like :

```
({
//    appDir: "../../",      //    ../../ pointing to webresources/javascript
    appDir: "${basedir}/src/main/webapp/webresources/javascript/",
    baseUrl: "./",
    dir: "${project.build.directory}/${project.build.finalName}/webresources/javascript/",

//    optimizeCss: "standard.keepLines",
    optimizeCss: "none",
    mainConfigFile: "${basedir}/src/main/webapp/webresources/javascript/edulastic/js/app.js",

    inlineText: true,
    removeCombined: false,
    wrapShim: 'true',
//    fileExclusionRegExp: /^(build|dist)/,
    modules: [
        {
            name: "edulastic/js/app",
            exclude: [
//            "jquery"
                "require-css/normalize",
                "swHelp"
            ]
        }
    ]
})
```

**Comment by nitinsurana** [comment]
Figured out the reason, I'm having variables in the path to .html files.

For e.g.
```
'text!' + cdnServer + '/template/index.html'
```

Is there a way to pass variables to r.js for the above scenario ?
