### ISSUE TITLE
How can I pass Closure Compiler options to r.js in command line?

### ISSUE THREAD

**Issue by disolovyov** [jrburke/r.js#128]
Hi!

I looked at the [example build.js file](https://github.com/jrburke/r.js/blob/master/build/example.build.js) and there's a section for Closure called `CompilerOptions`, but no examples how to set anything in it (just an empty object).

Tried passing an argument like `closure.CompilerOptions.languageIn=ECMASCRIPT5_STRICT` to r.js in command line, but that doesn't work. And it probably makes no sense?

Is there a way to pass such an option? Specifically, tell r.js to tell closure to keep `'use strict';` directives.

Thanks.

**Comment by balee** [comment]
It is a bit old, but the workaround approach does not work in v2.3.6:
java.lang.ClassCastException: Cannot cast java.lang.String to com.google.javascript.jscomp.CompilerOptions$LanguageMode
