### ISSUE TITLE
Lack of regexps while using namespace in r.js

### ISSUE THREAD

**Issue by Kasheftin** [jrburke/r.js#341]
I use namespace in optimizing process of my files. My files include jquery and knockoutjs. And there's such bug.

Jquery works correctly after optimization, because string 
```javascript
if ( typeof define === "function" && define.amd && define.amd.jQuery ) 
```
turns into
```javascript
if ( typeof namespace.define === "function" && namespace.define.amd && namespace.define.amd.jQuery ) 
```
Knockout has the similar string:
```javascript
if (typeof define === 'function' && define['amd'])
```
and this string is not processed. This will work if we replace define['amd'] with define.amd (this case defineCheckRegexp, r.js:20289 suits).

I don't ask to add one more regex into pragma array, there're already a lot of them. But here we have lack of logic, it seems that using regular expressions is not the right way at all. What if jquery changes the order of conditions next release?

**Comment by jrburke** [comment]
Using #871 to track the general conversion to an AST process, will close this one out now.
