### ISSUE TITLE
Some UglifyJS2 options are not exposed in r.js 2.1.2

### ISSUE THREAD

**Issue by saunders99999** [jrburke/r.js#342]
I am using **r.js 2.1.2** with config option, **optimize: "uglify2"**

**I see this in example.build.js**
`//If using UglifyJS for script optimization, these config options can be
    //used to pass configuration values to UglifyJS.
    //See https://github.com/mishoo/UglifyJS2 for possible values.
    uglify2: {},`

I tried adding the below in my r.js config and found it **does not work.**
    `uglify2: {beautify: true},`

**Looking closer at r.js and UglifyJS2, I'm expecting these are the UglifyJS2 options intended to be available.**
**http://lisperator.net/uglifyjs/codegen**
**http://lisperator.net/uglifyjs/compress**

When modifying r.js line 19126
**from**
`var stream = UglifyJS.OutputStream({ source_map: map });`

**to**
`var stream = UglifyJS.OutputStream({ source_map: map, beautify: true });`

I get my 'beautiful' output.

**_Questions**_
1.  Can you fix r.js so I can use **all the codegen/compress UglifyJS2** options?
2.  For clarity, **UglifyJS2** options are configured in r.js solely in the **uglify2** setting, not the **uglify** setting, right?
3.  Does **uglify2** have an equivalent of the **uglify.no_mangle** setting shown in example.build.js?

**Comment by Download** [comment]
Sorry to post here, but I've been looking all over and this page keeps coming up...

I'm trying to achieve the same as @soundstep, but I'm trying to do it for UglifyJS2...

I've tried all kinds of combinations for the mangle options but the only one I've got working so far is `mangle:false`:

	uglify2: {
		mangle: false
	}					

I'd like to pass an array of names to be ignored when mangling. However this does not seem to work:

	uglify2: {
		mangle: {
			except: ['myArg']
		}
	}					

Neither does this:

	uglify2: {
		mangle: true,
		except: ['myArg']
	}					

Is there an example of how to do this somewhere?
Is it confirmed that this is even possible?

As an extra complication I'm using r.js via a Grunt... So this config is in my gruntfile.js.

**Comment by Download** [comment]
Ok... Ever so sorry... I don't know what I was doing but it turns out that this does in fact work:

```javascript
uglify2: {
    mangle: {
        except: ['myArg']
    }
}
```

**Comment by JoolsCaesar** [comment]
Is there a way to access the includeSources source map option? It seems that sources are being added to sourcesContent in the source map by default. No matter where I put the includeSources option in the config it doesn't seem to have any affect.
