### ISSUE TITLE
Problem with running on windows 7

### ISSUE THREAD

**Issue by lobopl** [jrburke/r.js#369]
Hey I installed requirejs via npm install -g requirejs in windows 7. I try to compile example project in several ways and it isn't working:

```
r.js.cmd webapp/scripts/app.build.js
```

get nothing (nothing compiles) no errors

```
r.js webapp/scripts/app.build.js
```

get windows alert

```
---------------------------
Windows Script Host
---------------------------
Skrypt: C:\Users\lobo\AppData\Roaming\npm\r.js
Wiersz: 1
Znak:   1
Błąd: Invalid character
Kod:    800A03F6
Źródło:  Microsoft JScript compilation error

---------------------------
OK   
---------------------------
```

How i can fix it?

Ok my bad I runned r.js.cmd webapp/scripts/app.build.js and it worked

**Comment by mooop12** [comment]
@foxbunny I get the same error and none of your solutions help. r.js works when I start it manually in the command prompt, but when some other node module references it, it fails. I'm using Gulp, and neither gulp-amd-optimizer nor gulp-requirejs-optimizer work.

**Comment by hollykarthi** [comment]
When I run gulp watch in command prompt, i getting same error mentioned in top. Any solution?

**Comment by ArpanTanna** [comment]
@jrburke Thanks, even after 3 years this solution is working :)

**Comment by jrburke** [comment]
A command alias for `r_js` was added a little while back, that should also work now.
