### ISSUE TITLE
r.js 2.1.3 (and greater) is four times slower than 2.1.2

### ISSUE THREAD

**Issue by mdaniel** [jrburke/r.js#451]
``` sh
$ wget -O r-2.1.2.js https://github.com/jrburke/r.js/raw/2.1.2/dist/r.js
$ time /usr/bin/node r-2.1.2.js -o target/js-config/app.build.js
real    1m9.357s
user    1m8.717s
sys 0m0.498s
```

``` sh
$ wget -O r-2.1.3.js https://github.com/jrburke/r.js/raw/2.1.3/dist/r.js
$ time /usr/bin/node r-2.1.3.js -o target/js-config/app.build.js
real    4m31.063s
user    4m29.710s
sys 0m0.876s
```

``` sh
https://raw.github.com/jrburke/r.js/2.1.4/dist/r.js
real    4m27.894s
user    4m26.718s
sys 0m0.743s
```

``` sh
https://raw.github.com/jrburke/r.js/2.1.5/dist/r.js
real    4m27.136s
user    4m26.043s
sys 0m0.698s
```

``` sh
https://raw.github.com/jrburke/r.js/2.1.6/dist/r.js
real    4m40.676s
user    4m39.208s
sys 0m0.895s
```

This is with nodejs v0.10.7, Linux amd64.

app.build.js is {
    "optimize": "uglify2"
  , "optimizeCss": "standard"
  , "generateSourceMaps":true
  , "preserveLicenseComments":false
  , "useStrict": true
} // and some other parts that I doubt are relevant; let me know if you need the specifics

**Comment by gamelover42** [comment]
I'm not sure if this is related to the problem described above but it is worth mentioning that there is a known performance issue with uglify2 and pre-minified files https://github.com/mishoo/UglifyJS2/issues/321
