### ISSUE TITLE
r.js: command not found

### ISSUE THREAD

**Issue by raldred** [jrburke/r.js#488]
Maybe I'm going crazy, but the r.js command does not work after installing requirejs via npm

$ npm install requirejs --save
$ r.js -o build.js 
-bash: r.js: command not found

node_modules dir is present...

```
.
├── Guardfile
├── README
├── build.js
├── node_modules
│   └── requirejs
│       ├── README.md
│       ├── bin
│       │   └── r.js
│       ├── package.json
│       └── require.js
├── package.json
```

Any ideas?
Thanks

**Comment by wangfengcool** [comment]
npm install -g
