### ISSUE TITLE
r fails on windows

### ISSUE THREAD

**Issue by Pomax** [jrburke/r.js#551]
installing with `npm install -g requirejs` and then calling `r`, in windows 7 at least, opens a bash script in a text editor (a script that assumes cygwin is being used, too, which might not be the case. Windows users could just as well be using msys or another gnu tools alternative).

`npm` and friends get around this problem by having a bash script for the plain command that kicks in on bash-enabled systems, and a [command].cmd for windows (in this case `r.cmd`), where the cmd file is basically just a glorified .bat file that tells windows what to do. This would probably work well for 'r' as well.

**Comment by mborman** [comment]
Old topic I know, but would it be feasible to create a _second_ set of executables that are named `r-js` and `r-js.cmd`? It dirties up the `.bin` a bit but it would resolve the windows woes and would not break existing builds.
