### ISSUE TITLE
Removing console.log

### ISSUE THREAD

**Issue by Hesesses** [jrburke/r.js#583]
I have this in my build config:

onBuildRead: function (moduleName, path, contents) {
        //return contents;
        return contents.replace(/console.log(.*);/g, '');
    }

But that does nothing... Any ideas whats wrong?

**Comment by Kogoruhn** [comment]
@Hesesses  try `/(console\.)?(log\ *\(.*\)\ *;*)/g`

It can work with
```
console.log()
console.log();
console.log   ()       ;

log()
...
```
