### ISSUE TITLE
Uglify operation on CommonJS wrapped require spawns "not defined for context" error

### ISSUE THREAD

**Issue by markfeimer** [jrburke/r.js#606]
For background, I am using grunt-contrib-requirejs as part of a grunt build.  The idea is to create one output file for deployment.

Running r.js works correctly if I do not use the "optimize" option.

However, once I use "optimize: uglify" I get the following context error on page:

```
Uncaught Error: Module name "src/js/directions" has not been loaded yet for context: _
```

The error revolves around this line in my concatenated, non-optimized version):

```
define(function(require,exports,module) {
  var library = require('src/js/directions');
  module.exports = library;
});
```

Which, when optimized, becomes this:

```
define(function(e,t,n){var r=e("src/js/directions");n.exports=r});
```

A quick search pointed me to some issues around the CommonJS wrapper pattern and minification, so I tried hand-editing the minified file to this:

```
define(function(require,t,n){var i=require("src/js/directions");n.exports=i})
```

and everything worked correctly.

When I found this bug, https://github.com/jrburke/r.js/issues/125, I thought that I was just using a very old version of requirejs, but I'm currently on 2.1.9.  Since this may be related to issue #125 I wanted to see if it had re-emerged or if the issue rests with my optimization options.  Thanks!

**Comment by zepumph** [comment]
@markfeimer thank you for following through on this post. I just ran across this and it fixed my problem exactly!
