### ISSUE TITLE
Unable to leverage `allowSourceOverwrites` option?

### ISSUE THREAD

**Issue by cbaxter** [jrburke/r.js#629]
This is likely a misunderstanding on my part regarding the new allowSourceOverwrites option introduced in Issue #479.

Command:
```
r.js.cmd -o <path>\build.js dir=<path> appDir=<path>\js
```
Configuration:
```
({
    baseUrl: '.',
    keepBuildDir: true,
    allowSourceOverwrites: true,
    mainConfigFile: './js/main.js',
    paths: {
        ...
    },
    modules: [{
            ...
    ]
})
```

Resulting in the error 
```
Module ID 'main' has a source path that is same as output path: <path>/main.js. Stopping, config is malformed.
```

The error originates from r.js v2.1.11 @ line 25999 where the build path is checked against the sourcePath. With allowSourceOverwrites being `true` should this not be allowed? I am using the build in the same scenario as described in #479 where my source is build output and I would prefer to overwrite the source rather than do an extra copy.

**Comment by peol** [comment]
@jrburke : I can confirm that changing `if (module._buildPath === module._sourcePath) {` to `if (module._buildPath === module._sourcePath && !config.allowSourceOverwrites) {` fixes this specific issue and I got a working build folder.
