### ISSUE TITLE
Don't strip function-level "use strict" by default

### ISSUE THREAD

**Issue by lachlanhunt** [jrburke/r.js#689]
When a "use strict" statement occurs inside a function, it is harmless for optimisation and concatenation and should be left in by default.  Global "use strict" statements are harmful for optimisation, due to the risk of combining strict and non-strict code, so it is sensible to strip those by default.

i.e.  This should not be stripped because it is safe:

    define(["foo/bar"], function(fooBar) {
        "use strict";
    }

But this should be stripped because it is unsafe:

    "use strict";
    define(["foo/bar"], function(fooBar) {
        ...
    }

The useStrict option currently only allows true or false, so it either strips all of them, or leaves all of them. There needs to be a 3rd option to only strip the unsafe "use strict" statements, and that should also be the default.

**Comment by jrburke** [comment]
This came up again in #776, specifically with the JSXTransformer thing. While I may not be able to convert to a full AST transform for this step, see if something can be done.

**Comment by jrburke** [comment]
The [latest master snapshot](https://raw.githubusercontent.com/jrburke/r.js/master/dist/r.js) has a fix for this. It is still regexp based, but should be better than before, and not mess up JSXTransformer.
