### ISSUE TITLE
addModules plugin api to allow plugins to add a module and its dependencies in a layer.

### ISSUE THREAD

**Issue by clmath** [jrburke/r.js#696]
Hi,

Currently, the plugin API only allow to add a module in a layer from a string using the `write` method. This is perfectly fine for simple modules like AMD-wrapped html templates or nls bundles but it is very limited when dealing with real AMD modules.

A use case for this is the dojo has plugin. This plugin is made to conditionally load a module  or another depending on the environment. During the build, some of this conditions can already be solved, so the plugin know which module to include in the layer.

The problem is if the has plugin use the `write` method to include the module, this module's dependencies will not be included in the layer. The `addModules` function would solve this issue by allowing a plugin to directly give to the build the list of mids to be included in the layer with their dependencies.

Here is the API I propose: 

```
addModules(pluginName, resource, addModules)
```
- pluginName: String. The normalized name for the plugin.
- resource: String. The normalized resource name.
- addModules: Function.     A function to be called with an array of normalized module ids. Those modules and their dependencies will be included in the layer.

I don't know how hard that would be to implement but I think it would be really helpful.

**Comment by mc007** [comment]
I confirm this too, 'has' plugins are ignored during build time (grunt-requirejs). How to fix this now? Its definitely a show stopper. I was somehow happy to move to requirejs from dojo but now I really don't know how to proceed. 
thank you
