### ISSUE TITLE
Optimizing packages with names containing a "/"

### ISSUE THREAD

**Issue by KidkArolis** [jrburke/r.js#725]
I was wondering if you'd consider fixing the issue where currently package names with a slash, e.g. "@foo/bar" don't get optimized like other packages.

Scoped packages is a new feature in npm, and "@foo/bar" is a valid package name in npm from now on. We're building something on top of npm and require.js and our config looks like this at the moment:

```js
packages: [{
  name: "@foo/bar@1.0.0",
  main: "index",
  location: "@foo/bar@1.0.0"
}, {
  name: "baz@2.0.0",
  main: "index",
  location: "baz@2.0.0"
}]
```

However, after optimization, baz package is optimized as expected, but optimizing @foo/bar doesn't work the same way. In particular, in the output we get something like

```js
define("baz@2.0.0/index", [], function () {...});
define("baz@2.0.0", ["baz@2.0.0/index"], function (main) {return main;});
define("@foo/bar@1.0.0/index", [], function () {...});
```

What's missing there is

```js
define("@foo/bar@1.0.0", ["@foo/bar@1.0.0/index"], function (main) { return main; });
```

**Comment by KidkArolis** [comment]
Hi, James. Thanks for addressing this issue. We're still using this setup and require.js in production and I came across something peculiar. We're still on 2.1.15 btw (due to the esprima slow down in 2.1.16 which we can afford since our builds are dynamically run as part of our product).

In 2.1.16 you introduce the adapter module generation for multisegmented package names. That's all good, and essentially solved the issue I described.

However, today I realised that even if there is no adapter module, I can still do `require('@foo/bar@1.0.0') and that works, because of this code in `require.js`:

```js
// If the name points to a package's name, use
// the package main instead.
pkgMain = getOwn(config.pkgs, name);
```

So now, I'm confused why I needed the adapter module.

Anyways, this is not a real issue, I just found this very surprising as I can't remember why this didn't work for me back in 2014 and works fine now. The only thing I can think of is: if you don't have config.packages at runtime (only at buildtime), then the adapter module is needed. Could there be another explanation for this..?

**Comment by jrburke** [comment]
That sounds right: the goal of writing the adapter modules was to avoid the need for the config at runtime after a build. But if the packages config is there maybe it works out. Not sure if 2.1.15 if it is not creating the right adapter module if it would interfere with that config, something to check if you try it.
