### ISSUE TITLE
Short-config array for shim deps not working properly with wrapShim option

### ISSUE THREAD

**Issue by acasademont** [jrburke/r.js#744]
If I have my shim config defined like this, with the short config:

`
{
    shim: {
        'a': ['b']
    }
}
`

and 'wrapShim` option set, the dependencies are not correctly read.

Whereas if I define the shims in the full style:

`
{
    shim: {
        'a': {
            deps: ['b']
         }
    }
}
`

the dependencies in the shims are correctly wrapped.

Thanks!

**Comment by jorrit** [comment]
I think this was fixed with issue #813.

**Comment by acasademont** [comment]
thanks, i'll give it a try asap

**Comment by jrburke** [comment]
Closing given comments but we can reopen later if needed.
