### ISSUE TITLE
Typescript config file considered malformed by r.js

### ISSUE THREAD

**Issue by macromaniac** [jrburke/r.js#767]
my require-config.ts looks like:

    ({
    //Config stuff
    })

the transcompiled require-config.js looks like:

    ({
    //Config stuff
    )};
    //# sourceMappingURL=require-config.js.map

and

    r.js.cmd -o require-config.js 

gives me a config.js is malformed: SyntaxError: unexpected token ;

Both the source map and the ";" interfere with the build. Maybe consider using a more descriptive error message or making r.js more lenient towards these sorts of things.

**Comment by alexdresko** [comment]
Running into the same issue. I'm not even sure ({...})[;] is valid javascript to begin with.. at least according to jslint and jsonlint...

**Comment by jrburke** [comment]
Does the config file need to be a .ts file to start? If just a .js file and not run through the typescript compiler, and the contents do not contain typescript, what about that?

**Comment by macromaniac** [comment]
Haha clearly that works and that's what I ended up doing, was just frustrated I lost 2 hours on the assumption that I could write the config file in typescript then use the compiled javascript. Looking at the relevant source I imagine the purpose of the "("s in this line

    buildFileConfig = eval("(" + buildFileContents + ")");

is to throw an error when people throw in any old js file as the config file so they can be like "oh snap, I'm using main.js instead of build.js". It may or may not be worth fixing, but I think that a decent % of people that use typescript will try to use typescript for as much of their project as possible and thus will run into this problem. Least it's on google now I guess.

**Comment by macromaniac** [comment]
What happened was that I got this semicolon error and I had a pretty big build.js with lots of semicolons in it so I had to try to figure out which one was causing the problem. The error message was cryptic because it had no line numbers. I was tunnel visioned on my typescript file, and google wasn't helping. 

I think adding an error message like this would have saved me a lot of time, but the code isn't super pretty.

    var ensureValidFormat= /^\s*\(\{[\s\S]*\}\)\s*$/m;
    if(ensureValidFormat.test(buildFileContents)==false)
        throw new Error("The build file " + buildfilename + " needs to be of the format: ({...})");

The absolute dream is to have eval tell you the line number the error is on, but that feature is not supported in node atm. I think it's fine for you not to accept a trans-compiled build file in retrospect, it just stinks that this pitfall exists.

**Comment by alexdresko** [comment]
Of course, we can use the build config in a .js file, but we lose the opportunity to have a type-safe config file. The .d.ts file at https://github.com/borisyankov/DefinitelyTyped/blob/master/requirejs/require.d.ts enables TS developers to define their config object as a specific type. Along with more defined intellisense, it shows up as a compilation error if we type something wrong in the build config..

**Comment by jrburke** [comment]
2.1.16 will try to strip off the extra stuff at the bottom of the file if it looks like the one in comment 1, to allow it to be consumed.

**Comment by alexdresko** [comment]
Rad.
