### ISSUE TITLE
Optimizer breaks when using generator functions

### ISSUE THREAD

**Issue by mehranhatami** [jrburke/r.js#769]
Hi,
I am using `r.js` in my build process and it works really great.
But The point is, I am also using __generator functions__([function*](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/function*)) in couple of my AMD modules, like:

```javascript
//asyncStuff.js
define(['./utils'], function (utils) {
  return {
    aGeneratorFunction: function * () {
      var myAsyncStuff = yield utils.getMyAsyncStuff();
      //my async process continues
    }
  };
});
```
But it seems `r.js` doesn't tolerate the `*` sign and I get this:
```
Warning: Error: Parse error using esprima for file: /Users/.../asyncStuff.js
Error: Line 12: Unexpected token *
In module tree:
    asyncStuff

    at /Users/.../node_modules/requirejs/bin/r.js:26061:31
 Use --force to continue.

Aborted due to warnings.
```
After some digging through the `r.js` code I managed to fix it using a hack by replacing the builtin version of the [esprima](https://github.com/ariya/esprima) parser in `r.js` with the latest version of the [esprima](https://github.com/ariya/esprima) but it still needed me to hack part of the `r.js` code.

Could it be possible to fix it by passing a sort of option to the `r.js` optimizer?

**Comment by mehranhatami** [comment]
I managed to fix it with a temporary solution:
As I copied [esprima.js](https://github.com/ariya/esprima/blob/harmony/esprima.js) file from [harmony](https://github.com/ariya/esprima/tree/harmony) branch of the [esprima](https://github.com/ariya/esprima) repo and pasted it manually in the `r.js` file over the old esprima version used in `r.js`. And now everything works as expected.

As I see there could be two approaches to solve this issue, making a new branch name `harmony` or adding a new argument to the `optimizer` to enable ES6/Harmony functionality support.

**Comment by jrburke** [comment]
I believe the following should work, please post back if it does not. This assumes you are running in node/iojs:

```javascript
// This assumes the esprima you get is the harmony branch one.
var esprima = require('esprima'),
    requirejs = require('requirejs');

//Register the replacement module.
requirejs.define('esprima', [], function () {
    return esprima;
});

//Do the build.
requirejs.optimize({
    baseUrl: "../../../../../requirejs/tests",
    name: "one",
    include: "other",
    out: "one-built.js",
    //Usually requirejs.optimize() runs in "silent mode"
    //when called in this way. Use logLevel to get the
    //normal output out.
    logLevel: 0
}, function () {
    //Do not really care about the build output summary,
    //since the logLevel: 0 will show it anyway in the console.
}, function(err) {
    //Called if error.
});
```

In general, I prefer to not include the harmony esprima in r.js as I feel it is subject to more swirl, or to get bogged down in incorrect parsing due to es6 not being done. For the immediate future, I will suggest this pathway, and will close this bug as the above workaround for the solution.

Once es6 stabilizes and esprima feels it is safe to ship an es6-capable parser by default, then it will just be a matter of the latest r.js release picking it up in its normal release cycle.
