### ISSUE TITLE
Fails to optimize code that uses rjs plugin and violates strict mode

### ISSUE THREAD

**Issue by emirotin** [jrburke/r.js#774]
I have a piece of code (it's 3rd party) that violates strict mode rule: "In strict mode code, functions can only be declared at top level". The code lives inside of a CoffeeScript file.

The code works in the browser, but fails with r.js because of this line: 

```
/**
 * This adapter assumes that x.js has loaded it and set up
 * some variables. This adapter just allows limited RequireJS
 * usage from within the requirejs directory. The general
 * node adapater is r.js.
 */

(function () {
    'use strict'; // <!-- here

    var nodeReq = requirejsVars.nodeRequire,
```

So when my code is transpiled and then `eval`ed in `req.exec` that happens inside of the strict mode function and fails.

**Comment by jrburke** [comment]
So to confirm, this happens when running r.js with node, but just executing some modules, not doing an optimization step?

**Comment by emirotin** [comment]
Yes, combining the files, processing CoffeeScript, but not minifying.

As far as I understand that's because `eval` runs inside of the strict function.

This doesn't happen if I move the dame code to pure JS file because in that case the code doesn't go through `eval` — that's how I fixed it for my project.

As far as I remember I verified that removing that line in r.js helps.

**Comment by jrburke** [comment]
I want to be sure I can generate a test case to prevent the failure from happening again, so not sure I follow yet, and happy to have pointers to the type of thing that failed, or a small test case.

Was this from `node r.js app.js` to run some AMD modules in node as part of an app not related to module bundling, or by calling the optimizer to build/combine files together, something like `node r.js -o buildconfig.js`? 

If the build situation, I believe this sort of eval issue would only show up when loader plugins are involved. If that is the case, perhaps a pointer to the loader plugin if that is helpful.

**Comment by emirotin** [comment]
Oh, I misunderstood your initial question, sorry. So it _was_ optimization (building JS for the browser).

I use the loader because I use CoffeeScript. The plugin is this https://github.com/resin-io/require-cs

Basically the scenario is: we have `main.js` that requires `module.coffee`. `module.coffee` has a piece of JS (embedded in triple backticks) that's not valid in strict mode. Then we build main.js. I will try to build it myself.
