### ISSUE TITLE
Update to esprima 2.0

### ISSUE THREAD

**Issue by jrburke** [jrburke/r.js#776]
It is an official release and supports some es6 features.

**Comment by jrburke** [comment]
This can be tried using the latest master snapshot:

https://raw.githubusercontent.com/jrburke/r.js/master/dist/r.js

**Comment by philix** [comment]
I'm still having problems with `"use strict"` strings on http://github.com/philix/jsx-requirejs-plugin. I pushed a branch with the new `requirejs` and Facebook's original `JSXTransformer.js` [1]. I was optimistic that it would work and didn't try it before the requirejs release, but for some reason it doesn't. I wonder if esprima 2.0 can really handle "use strict" string literals.

```
$ node r.js -v
r.js: 2.1.16, RequireJS: 2.1.16, UglifyJS2: 2.4.16, UglifyJS: 1.3.4
$ node r.js -o build.js

Tracing dependencies for: main
Error: Parse error using esprima for file: /Users/felipe/code/jsx-requirejs-plugin/build_js/JSXTransformer.js
Error: Line 11877: Unexpected token if
In module tree:
    main
      jsx

Error: Error: Parse error using esprima for file: /Users/felipe/code/jsx-requirejs-plugin/build_js/JSXTransformer.js
Error: Line 11877: Unexpected token if
In module tree:
    main
      jsx

    at /Users/felipe/code/jsx-requirejs-plugin/r.js:26148:47
```

[1] https://github.com/philix/jsx-requirejs-plugin/tree/esprima2

**Comment by philix** [comment]
@DimitarChristoff check this.

**Comment by jrburke** [comment]
This happens because of the aggressive, and in this case incorrect, `use strict` stripping done in r.js. If you set `useStrict: true` in the build config, it should complete the build. I'll see if I can do something that makes it less likely to cause problems, tracked in #689.
