### ISSUE TITLE
Single-character typo on http://requirejs.org/docs/node.html

### ISSUE THREAD

**Issue by JonathanHayward** [jrburke/r.js#782]
http://requirejs.org/docs/node.html has, towards the bottom:

The optimizer running in Node **if** fairly fast, but for larger projects that do not want to regenerate the build for every browser request, but just if you modify a script that is part of the build.

That should probably be:

The optimizer running in Node **is** fairly fast, but for larger projects that do not want to regenerate the build for every browser request, but just if you modify a script that is part of the build.

**Comment by jrburke** [comment]
Fixed in https://github.com/jrburke/requirejs/commit/341d97179320080cdc3c6566e244385a43b41b6a, and site updated, thank you!

**Comment by JonathanHayward** [comment]
You're welcome! Thank you for require.js the tool and requirejs.org the site.

Best,
