### ISSUE TITLE
removeStrict() regex causes valid code to fail to parse

### ISSUE THREAD

**Issue by sufianrhazi** [jrburke/r.js#786]
If you have the following valid javascript and config.useStrict is false:

    var x = 'use strict';
    if (true) {
        console.log('do something');
    }

r.js will strip out the "'use strict';", resulting in the following invalid code:

    var x = 
    if (true) {
        console.log('do something');
    }

Which will fail to be parsed by esprima.

The offending code is in: https://github.com/jrburke/r.js/blob/master/build/jslib/pragma.js#L47-L49

**Comment by jrburke** [comment]
This should be fixed by #689, which is fixed in master, and will be part of the 2.1.17 release.
