### ISSUE TITLE
Concatenation of modules with inner anonymous modules fails silently

### ISSUE THREAD

**Issue by mokkabonna** [jrburke/r.js#797]
See https://github.com/openlayers/ol3/issues/3389

Now it outputs this, the first part is just the file as it is (no name added as it should) and then it inserts `define("ol", function(){});` after:
```javascript
(function (root, factory) {
  if (typeof define === "function" && define.amd) {
    define([], factory); //<= optimizer trips totally in this case and does nothing, then below creates ol as an empty function 
  } else if (typeof exports === "object") {
    module.exports = factory();
  } else {
    root.ol = factory();
  }
}(this, function () {
  var OPENLAYERS = {};
  //not relevant code snipped
  if("function"===typeof define && define.amd) define(function (){return {};});
  //not relevant code snipped

  return OPENLAYERS.ol;
}));

define("ol", function(){});
```

I know this is a wrong way to write modules, but still it would be great if r.js let us know that this happened and failed rather than creating the above output. If possible. Not sure how the parsing works with r.js. Might be hard to do if done in a certain way I can imagine.

**Comment by jrburke** [comment]
What version of r.js was used? I have had done some fixes, and thought this would be supported now, at least with 2.1.16.

**Comment by mokkabonna** [comment]
The moment has passed for this, not sure anymore, closing.
