### ISSUE TITLE
Weird error "Nope"

### ISSUE THREAD

**Issue by kirill-konshin** [jrburke/r.js#810]
```
Error: nope
    at check (/home/jenkins/tmp/web/src/app/node_modules/requirejs/bin/r.js:2789:23)
```

No extra explanations or data. Can you please make an error more self-explanatory.

**Comment by kirill-konshin** [comment]
```js
    function check(p) {
        if (hasProp(p, 'e') || hasProp(p, 'v')) {
            if (!prim.hideResolutionConflict) {
                throw new Error('nope' + JSON.stringify(p));
            }
            return false;
        }
        return true;
    }
```

This gave enough debug info.

**Comment by jrburke** [comment]
Ah yes, that is from an older promise shim I made. I probably would do it differently now, but at the time I wanted to be sure to catch code that was trying to resolve too many times. Real promises do not expose that, but it helped me catch some bugs while moving some of the internals to that model. I updated the message based on your suggestion.
