### ISSUE TITLE
Is there a way to add pre-load hook

### ISSUE THREAD

**Issue by kirill-konshin** [jrburke/r.js#812]
As an example, it would be very convenient to add some transformations to the path of the file before it actually is loaded, for example, prepend all `*.json` files with `json!` or `text!` plugins so that there will be no need to specify plugin every time.

**Comment by kirill-konshin** [comment]
Bump!

**Comment by jrburke** [comment]
There is not a general hook for this. I am doing some experiments for a new loader core at [amodro-lifecycle](https://github.com/amodrojs/amodro-lifecycle), which would allow a top level imperative override of a `normalize` step.

So I am likely to get to those imperative overrides via that pathway, and likely in a different loader/repo than the requirejs repo. If you needed something in the meantime, `requirejs.s.contexts._.makeModuleMap` is the function used internally. However, that is considered a private API and no API stability is guaranteed for it.

Also be aware of the cost of this sort of override: it only makes sense in your own private app code: if wanting to share code with others, having a uniform ID structure, with loader plugins visible to indicate their dependencies, is important for easier code sharing.

Going to close as not planned for requirejs in particular, but I do want to get to an AMD loader with an overridable set of lifecycle steps.

**Comment by kirill-konshin** [comment]
Can I use this requirejs.s.contexts._.makeModuleMap during the build as well?

**Comment by jrburke** [comment]
Hmm, that might be harder to do. If you use the requirejs module [in a node program](http://requirejs.org/docs/node.html#optimizer), that might give you a way to add something there, but I don't recall if the whole of requirejs is visible in that case, and in the build, it uses the 'build' context instead of the default '_' one for build stuff. It will likely end up being very hacky, overall I do not recommend it.

**Comment by kirill-konshin** [comment]
OK, I'll try as is and share the outcome.

**Comment by kirill-konshin** [comment]
makeModuleMap is used everywhere as local function so replacing it in context does not give any results.

**Comment by kirill-konshin** [comment]
It would be great if you'll add an ability to make something very generic like:

```js
requirejs.beforeResolve = function(name){
    if (name.indexOf('.jsx')) name = 'jsx!' + name;
    return name;
};
```

Or some sort of interceptor of makeModuleMap's result with ability to alter it.

Seems to be very straightforward and will allow to get rid of numerous `jsx!` prefixes in React websites that use in-browser compilation.

**Comment by jrburke** [comment]
Ah right, I forgot internally it has a local ref to the original function. The best bet will be to wait for a different type of AMD loader that allows imperative overrides of the hooks. I don't plan on altering the internals of requirejs itself, at least in the 2.x lineage for this.

**Comment by kirill-konshin** [comment]
So in other words, there is nothing we can do right now with RequireJS, even the small hook right before the return statement of makeModuleMap?

Something like:

```js
            ...

            suffix = prefix && !pluginModule && !isNormalized ?
                     '_unnormalized' + (unnormalizedCounter += 1) :
                     '';

            var moduleInfo = {
                prefix: prefix,
                name: normalizedName,
                parentMap: parentModuleMap,
                unnormalized: !!suffix,
                url: url,
                originalName: originalName,
                isDefine: isDefine,
                id: (prefix ?
                        prefix + '!' + normalizedName :
                        normalizedName) + suffix
            };

            if (typeof req.beforeResolve == 'function') { res = req.beforeResolve(res); }
         
            return res;
```

This seems to be a minor change... should work the same as global `requirejs.onError` hook. Of course in API documentation we must explain to users that it's their own risk to use it in their project (but not in library, of course, no library should depend on this, but I think it's quite obvious).

**Comment by kirill-konshin** [comment]
Any updates regarding the proposed solution?

**Comment by jrburke** [comment]
Same thoughts as my last comment. I have been working on something that has more imperative overrides for the loader steps in [amodro-base](https://github.com/amodrojs/amodro-base), and while it is not very easy to consume it right now, it passes a lot of tests. No plans to do more in requirejs though.

**Comment by kirill-konshin** [comment]
As I mentioned earlier, simple hook would be enough...
