### ISSUE TITLE
"TypeError: undefined is not a function" when compiling code with dynamic dependencies

### ISSUE THREAD

**Issue by twpol** [jrburke/r.js#825]
I've got some code which dynamically determines which components to load (at runtime) and it does this by constructing an array of module names and calling `define`:

```js
var dependencies = [];
// Omitted: add to dependencies array.
define('loader', dependencies, function() { /* Omitted: code for initialisation. */ });
```

This works fine as-is, of course, but compiling with `r.js` chokes on the `define` with the following error:

```
>> Error: Parse error using esprima for file: (Omitted)/loader.js
>> TypeError: undefined is not a function
>> In module tree: (Omitted)
```

After some time (thanks for the helpful error, Node!) I tracked the problem down to this line in `parse.js`: https://github.com/jrburke/r.js/blob/2.1.18/build/jslib/parse.js#L184. It chokes because `moduleCall.deps` is not an array but instead a parsed identifier.

I'm not sure whether the code following that would also choke, but I've temporarily patched it by inserting the following above the `if`:

```js
if (typeof moduleCall.deps !== 'object' || typeof moduleCall.deps.length === 'undefined') {
    moduleCall.deps = [];
}
```

I'm not sure what your feelings are on such defines and I certainly do not expect it to figure out the possible dependencies, but at the very least I'd like the compilation to complete without fatal errors.

**Comment by jrburke** [comment]
I did the fix at a different place, in parseNode, where the initial shape of the define() call is done. Included a test too. You can try the latest [snapshot](https://raw.githubusercontent.com/jrburke/r.js/master/dist/r.js) if you want to test the change.
