### ISSUE TITLE
Support module config access OOB after optimization

### ISSUE THREAD

**Issue by RutledgePaulV** [jrburke/r.js#827]
I've read through #300 and decided to go ahead and open this issue anyway as I believe I can provide a handful of valid use cases for this (though I'll just provide one here unless asked for more). While I realize there may be ways around this I think it's generally a lacking / expected feature of the optimizer since typically any module config defined in the require config is available to the module at any time, not only before the first require (which I think is what #300 says?).

Consider this example:
I've defined an AJAX service library that determines the valid endpoints and required parameters so that it can do FE validation before sending a request. It's common to initiate this module with a data list of endpoints and parameters / types so that it can populate it's registry of functions. This initializing of the data occurs on the first require of the module, and may be provided as a browser global, an initial AJAX call to fetch it from the server, hardcoded, etc. 

In order for this module to be re-usable, I'd like to refrain from defining the mechanism in which this seed data is populated, and instead just want to read it from the module configuration. That way, a user simply includes the module in their project and configures it in their require config by implementing a function on the module config which then is read and utilized in the module itself on first require.

```
// inside require config
config: {
	commands: {
	       availableUrl: '/commands/available/',
	       executionUrl: '/commands/',

	        // the available commands are provided by the server as
		// templated data so that we don't have to make a second
		// ajax call immediately on load.
                commands: function() {
	                return window.__available__.commands;
                }
	}
},
```

I hope that this is seen as a reasonable request since it's a point of disparity between vanilla require.js and r optimized / almond configurations. Until then I'm happy to use the onBuild hook and handle it myself.

Of course, if this does happen be sure to note that the config values must either be statically defined or provided via a callback (since access to the window object and such won't be available when optimizer is typically run :)) I think that is a totally reasonable restriction to place on it's usage.

**Comment by RutledgePaulV** [comment]
So after looking at solutions for this I found that I can do the following:

I define an "include" script for my build that contains all of the module configuration and does a require immediately after defining. This gets inserted prior to any "insertRequire" scripts and so the module configuration is available in those modules at that point in time.

```
// build.js
(function () {
	return {
		wrapShim: true,
		optimizeCss: "none",
		optimize: "none",
		skipDirOptimize: false,
		preserveLicenseComments: false,
		mainConfigFile: 'config/require.js',

		// this piece embeds a define and require of the module configuration
		// just prior to the require() call provided by the insertRequire (which
		// is used to load the main for a given page. This is necessary because
		// commands depends on module configuration
		include: ['scripts/config/modules']
	}
}());
```

```
// scripts/config/modules.js
(function () {
	define(function () {

		require.config({
			config: {
				commands: {
					availableUrl: '/commands/available/',
					executionUrl: '/commands/',
					commands: window.__available__.commands
				}
			}
		});

	});

	require(['scripts/config/modules']);
}());
```

**Comment by jrburke** [comment]
That sounds like how I would do it too, would likely recommend, so closing out as a solution found.
