### ISSUE TITLE
RequireJS exclude ALL other folders than include

### ISSUE THREAD

**Issue by glraj** [jrburke/r.js#835]
I want requireJS to just use only the folder and files in the include configuration and do a blanket exclude of all other dependency from other folders and files.

I can put the folders to exclude in the paths as empty: but I am looking for a blanket consideration that requireJS only use the folder and files in the include configuration and rest it ignore.

I tried using findNestedDependencies but it didn't work I guess we can introduce a new flag for this type of requirement.

Thoughts?

  options: {
                        insertRequire: false,
                        baseUrl: 'build',
                        findNestedDependencies: false,
                        optimize: 'none',
                        out: outVar,
                        include: includeArray,
                        paths: {

Thanks - Raj

**Comment by jrburke** [comment]
It sounds like it is best to just concatenate the files together, and then make sure the define() calls get normalized to built define() calls with module IDs. You can just concat the files yourself, but to get the normalized define() calls, you could use the internal 'transform' module inside the r.js optimizer. A sketch of a program that could run in node to do this:

```javascript
var requirejs = require('requirejs');
requirejs.tools.useLib(function(require) {
  require(['transform'], function (transform) {
     //todo: generate a files array with the list of files to concatenate.

      files.forEach(function(filePath) {
        var fullPath = path.join(targetDir, filePath);
        var contents = fs.readFileSync(fullPath, 'utf8');
        var moduleId = /* todo, figure out what the moduleId is for the module */
        var transformed = transform
                          .toTransport('', moduleId, fullPath, contents);

        //todo: concat the contents together
      });
    });
  });
});
```

There are no plans to provide more declarative options for this sort of thing. [amodro-trace](https://github.com/amodrojs/amodro-trace) might be another way to do this, but then just prune the result to just contain the files and contents you want to concatenate.
