### ISSUE TITLE
can't find module dependence

### ISSUE THREAD

**Issue by gogoyqj** [jrburke/r.js#836]
config
```javascript
requirejs.config({
    baseUrl: "./",
    path: {
        tree: "./lib/ui/tree/main",
        live: "./lib/ui/live/main",
        ... many many alias...
    }
})
```
lib/ui/tree.js
```javascript
define(["../../live/main", "text./main.html"], function() {})
```

Here's the problem:
```javascript
requirejs(["tree"], function(){})
```
 "lib/ui/tree/main.js" is loaded successfully，But requirejs tried to load "main.html" && "../../live/main.js" instead of "lib/ui/tree/main.html" && "lib/ui/live/main.js"

How can I fix this problem?

appreciate for your suggestion

**Comment by jrburke** [comment]
It sounds like these are more like packages of functionality vs just a paths config. So I would use [packages config](http://requirejs.org/docs/api.html#packages), something like:

```javascript
requirejs.config({
    baseUrl: "./",
    packages: [
        {
            name: "tree",
            location: 'lib/ui/tree',
            main: "main"
        },
        {
            name: "live",
            location: 'lib/ui/live',
            main: "main"
        },
    ]
})
```

Then tree.js can just ask for `define(['live', 'text!./main.html'], ....);`
