### ISSUE TITLE
"browser" Being Detected as Environment instead of "node" in Atom Editor

### ISSUE THREAD

**Issue by DSpeckhals** [jrburke/r.js#840]
When I attempt to execute r.js in GitHub's Atom text editor (which is wrapped by a Chromium-based shell), the environment is being detected as "browser" instead of "node." The conditions for browser detection are:
```javascript
if ((typeof navigator !== 'undefined' && typeof document !== 'undefined') ||
        (typeof importScripts !== 'undefined' && typeof self !== 'undefined')) {
        env = 'browser';
        // etc...
} else if (typeof process !== 'undefined' && process.versions && !!process.versions.node) {
        env = 'node';
        // etc...
}
```
The issue here is that _both_ conditions evaluate to `true` in Atom, and that it's basically a matter of the ordering. Yes, Atom itself does have both `navigator` and `document` global variables (because it's essentially a browser), but node is what is actually executing this script. Perhaps the conditions could be made a little more applicable to an Atom environment, or even the condition ordering could be switched. This is my first time looking into the internals of r.js, so my knowledge of the best thing to do is slim. Please let me know what you think.

To give a little more detail, I am using an Atom plugin [atom-grunt-runner](https://github.com/nickclaw/atom-grunt-runner), which runs a node process that calls [grunt-contrib-requirejs](https://github.com/gruntjs/grunt-contrib-requirejs); that then attempts to execute requirejs and r.js version 2.1.19.

**Comment by jrburke** [comment]
A while back the text plugin merged a change to explicitly [not take the node route](https://github.com/requirejs/text/blob/26643989f5eab8df1f18c37f04a693036b941871/text.js#L243) if in one of these node-webkit/atomshell cases.

So I am unsure on the path to take for this, as allowing the r.js plugin to take the node route would likely break if the text loader plugin is used in that r.js build environment.

Ideally there would be a way in electron to fork a process in just stock node and let it run in there, as that would be the clearest statement of intent. Is that an option?

**Comment by DSpeckhals** [comment]
Yeah, I can see the conundrum with text.js. I guess this isn't _too_ big of an issue -- I'm not seeing any obvious exceptions now that I look closer. I originally thought this was causing problems downstream in Grunt, but it was not.

**Comment by jrburke** [comment]
OK, I will close this for now, but we can add to the ticket over time if an issue comes up with it.

**Comment by DSpeckhals** [comment]
Well, after some further research, I take back what I said earlier; it does look like this causes an issue when running from a Grunt task in the Atom/Electron environment. With the `env` being detected as a browser, there are a few failures that happen, as you can imagine. One example is that r.js attempts to [get the `head` element of the `document`](https://github.com/jrburke/r.js/blob/801bf683d3183171b8385950d00cd9894ed0b09b/require.js#L1823), which Node does not have.

I modified r.js code locally to detect Electron as `node` in r.js, and the problems cease. I actually use the text.js plugin in builds, and I did not receive any failures when running optimize. Is there a chance that we could try to find a good solution for this?
