### ISSUE TITLE
Dramatic increase in build time in r.js version 2.1.16, as compared to 2.1.15

### ISSUE THREAD

**Issue by joutsen** [jrburke/r.js#850]
2.1.16 requirejs build time is 4 times larger than 2.1.15 with findNestedDependencies: true.
The issue is reported in StackOverflow http://stackoverflow.com/questions/29987399/is-r-js-dependency-tracing-significantly-slower-since-v2-1-16-or-is-it-just-me
It is visible both on Windows and Linux.
My Gruntfile.js config is
```javascript
requirejs: {
            options: {
                baseUrl: '<%= config.app %>/assets/js',
                optimize: 'none',
                mainConfigFile: '<%= config.app %>/assets/js/config.js',
                findNestedDependencies: true,
                exclude: [
                    'knockout'
                ]
            },
            my_lib: {
                options: {
                    name: 'my_lib',
                    out: '<%= config.dist %>/assets/js/my_lib.js'
                }
            }
       }
```
Versions:
node: 0.10.38
grunt: 0.4.5
grunt-contrib-requirejs: 0.4.4
requirejs: 2.1.16 (the first one with the issue)
Ubuntu Linux 14.04

Same problem is reported on Windows 7.
Another reported config:
```javascript
{
    baseUrl: 'some/path/here',
    mainConfigFile: 'some/path/here',
    dir: 'some/path/here',
    modules: [
        {
            name: "base"
        },
        {
            name: "specific",
            exclude: ["base"]
        }
    ],
    findNestedDependencies: true,
    removeCombined: true,
    skipDirOptimize: true,
    optimize: "none"
}
```

**Comment by jrburke** [comment]
This lists the full set of changes between 2.1.15 and 2.1.16 for the optimizer:
https://github.com/jrburke/requirejs/compare/2.1.15...2.1.16

This was the set of bugs tracked for 2.1.16:
https://github.com/jrburke/r.js/issues?q=milestone%3A2.1.16

As the stackoverflow answer suggests, it is likely either the move to Esprima 2.0 or the update to uglifyjs if you are using uglify2 in the build.

https://github.com/jrburke/r.js/issues/733 is the only r.js non-vendor code to change for the parsing part, and it is not a big diff in parse.js for it, so I suspect it is the esprima or uglifyjs change. If uglify, set "optimize" to "none" to see if that helps. If esprima, then I have updated esprima in later r.js releases to newer versions so a later r.js version than 2.1.16 might be worth a try.

The other option is for someone to do some profiling with another parser, maybe acorn, to see if it would be better to use than esprima. However, at the moment, the main driver for parser updates is to get ES2015 syntax updates, so I would want something that can keep pace with that. Esprima seems to be fairly focused on full coverage, but I do not follow the parser options fairly closely.

Going to close for now as I suspect that is the issue, and no update to a 2.1.16 for this is expected. For swapping out esprima with another parser, a separate targeted ticket that can track profiling of the specific option should be opened. If further experiments show that there is a tweak that can be done in r.js without swapping out esprima, then we can reopen this ticket, and feel free to continue discussion here.

**Comment by joutsen** [comment]
I can confirm that 2.1.20 is as slow as 2.1.16 and is 4 times slower than 2.1.15 in our environment described above. So the latest upgrade of Esprima is unlikely to be a solution. Please note also that in both of reported cases `optimize: "none"`, so it is neither uglify to blame. Sad to see this closed, because such a drastic build performance degradation is an issue at least to our project.

**Comment by jrburke** [comment]
Possible fixes are engaging with the esprima community to get faster parse times, as this project will pick up any improvements there as they do releases. 

Or for someone to look at a more targeted test about trying out acorn as an alternative inside r.js. I do not have the bandwidth at the moment to try that, but it might be enough to copy in acorn.js contents into esprima.js in this project, maybe making sure acorn supports the same top level API as esprima. Then running `node dist.js` at the root of this project to generate an r.js. The r.js generated at the root of this repo can then be used for testing. A separate, acorn-specific issue with results/pull request is best in that case.

**Comment by KidkArolis** [comment]
I can also confirm this issue.. :( Build times:

* 2.1.15 - 8s
* 2.1.16 - 35s
* 2.1.20 - 54s

**Comment by rickychien** [comment]
https://www.npmjs.com/package/acorn-to-esprima

A possible quick fix would be acorn-to-esprima converter to transform an acorn/babel ast to esprima format directly. However, it might introduce an extra overhead during transforming.

**Comment by jrburke** [comment]
@rickychien thanks for the link, great to know about that! #900 just landed a change that seems to really reduce time spent in the parsing steps. If people that had slow build times want to try out the latest master snapshot:

https://raw.githubusercontent.com/jrburke/r.js/master/dist/r.js

that would help validate the change and the performance gain, at least under node.

acorn still might be a possibility longer term, but we'll see how far the most recent change helps.
