### ISSUE TITLE
requirejs loader inconsistent path resolution

### ISSUE THREAD

**Issue by alexindigo** [jrburke/r.js#853]
While trying to use amd-wrapped node modules in the browser, I noticed strange behavior of requirejs loader.

### Case 1:

Original file (`node_modules/save-property-actions/index.js`):

```js
module.exports = require('./save_property_actions');
```

After using commonJs and transform (from r.js) wrapped version looks like this:

```js
define('save-property-actions',
['require','exports','module','./save_property_actions'],
function (require, exports, module) {
  module.exports = require('./save_property_actions');
});
```

When it loaded from `localhost/js/save-property-actions.js`, subsequent request looks like following:

```
http://localhost/js/save_property_actions.js
```

Which is somewhat expected.

### Case 2:

Original file (`node_modules/save-property-actions/index.js`):

```js
module.exports = require('./save_property_actions.js'); // <--- with explicit extension 
```

After using commonJs and transform (from r.js) wrapped version looks like this:

```js
define('save-property-actions',
['require','exports','module','./save_property_actions.js'], // <--- with explicit extension 
function (require, exports, module) {
  module.exports = require('./save_property_actions.js');
});
```

When it loaded from `localhost/js/save-property-actions.js`, subsequent request looks like following:

```
http://localhost/save_property_actions.js
```

BasePath is gone. 

Is it happening by design or else?

Thank you.

**Comment by jrburke** [comment]
This sounds like [nodeIdCompat: true](http://requirejs.org/docs/api.html#config-nodeIdCompat) needs to be set in the requirejs.config for the runtime loader.

Going to close as I believe that is the issue, but feel free to continue discussion here and we can reopen as needed.
