### ISSUE TITLE
If path alias exists, exclude is shallow

### ISSUE THREAD

**Issue by arackaf** [jrburke/r.js#856]
For this run of r.js

```JavaScript
var rjs = require('requirejs');

var config = {
    name: 'a',
    out: 'a-build.js',
    baseUrl: './',
    optimize: 'none',
    paths: {
        foo: 'aliased'
    },
    exclude: ['text', 'aliased']
};

rjs.optimize(config, function (buildResponse) {
});
```

With this in aliased.js

```JavaScript
define(['helper-for-aliased'], function () {
    return { name: 'aliased-helper' };
});
```

The `helper-for-aliased` file winds up in the bundle.  But when the exclude array has the alias `foo` instead of the actual path, `aliased`, then the exclusion is deep, as it should be, with `helper-for-aliased` properly excluded from the bundle.

**Comment by jrburke** [comment]
This will be a problem: referring the module ID 'foo' to the file at ./aliased.js, but also using the 'aliased' as a module ID that resolves to the same file: if both are requested that will be an error, the define()'d module can only be claimed by one ID. If the bundle is also asking for 'foo', I expect that is the problem.

However, [map config](http://requirejs.org/docs/api.html#config-map) allows pointing other IDs to base IDs, I suggest trying that.

I think that is the root of the issue, so closing, but feel free to continue discussion here and we can reopen as needed.
