### ISSUE TITLE
Feature require/suggestion: add option to hash/obfuscate module names  

### ISSUE THREAD

**Issue by Bnaya** [jrburke/r.js#862]
When working with deep directory structure you can get very long modules names,
that repeating themselfs a lot of times in the optimzied file.
its possible to hash the names (in md5 or so) and it will make them shorter but still unique.

If there was a hook to rename modules and dependencies names it could be done in a method in the config file 

This code is illustrate the wanted behaviour, but it less robust then to hook into the build process.
```js
{
    onBuildWrite: function (moduleName, path, contents) {
        modules.push(moduleName);
        return contents;
    },
    onModuleBundleComplete: function (data) {
        function escapeRegExp(string){
            return string.replace(/[.*+?^${}()|[\]\\\!]/g, "\\$&");
        }

        var fs = module.require('fs'),
            code;

        code = fs.readFileSync(data.path, {
            encoding: 'utf8'
        });

        modules.sort(function (a, b) {
            return a.length > b.length ? -1 : 1;
        });

        modules.forEach(function (module, index) {
            code = code.replace(new RegExp("'" + escapeRegExp(module) + "'", 'g'), "'" + 'm' + index + "'");
        });

        fs.writeFileSync(data.path, code);
    }
}
```

**Comment by jrburke** [comment]
No plans to support this as it will not work in the general case: dynamic require() calls, like `require([viewName], function(){})`, would not be possible to rewrite. If using gzip to compress the files for delivery that should help reduce the overall impact. 

However, if this is desired in a particular project that does not have the dynamic require case, it does seem just having a separate post r.js process run over the string IDs would be a way to address it.
