### ISSUE TITLE
How to break r.js build in case of any javascript syntax errors?

### ISSUE THREAD

**Issue by Virbhadrasinh** [jrburke/r.js#866]
I am using r.js(2.1.16) and UglifyJS2 and I want to break the build if a file has  **Duplicate data property in object literal** or any javascript syntax error.
 
Now when I run r.js build with above mentioned errors; build is successful but while running application I am facing issues because of javascript syntax errors.

I have removed following try-catch block in r.js(line number: 24501) file and build started breaking (which is my requirement),

    //            try {
                    astRoot = esprima.parse(contents, {
                        loc: true
                    });
    //            } catch (e) {
    //                logger.trace('toTransport skipping ' + path + ': ' +
    //                             e.toString());
    //                return contents;
    //            }

Is there any configuration in r.js or UglifyJS2 by which the build can fail in such cases?

**Comment by jrburke** [comment]
There is no option for this in the optimizer, it is best to run a linting pass before doing the build, as a step outside of the r.js optimization step.
