### ISSUE TITLE
Require js load first module but not executing after optimized with r.js

### ISSUE THREAD

**Issue by jwerre** [jrburke/r.js#870]
I've built an app using require.js 2.1.20 and it works fine until I optimize it using r.js. After it's compiled the script defined in the "data-main" attribute loads but doesn't execute it. The strange thing is if I use require.js version 1.0.8 it works as expected. Any thoughts on why this could be happening? Here are the relevant scripts. 

**build.js**

	{
		"baseUrl": "javascript/libs",
		"appDir": "../static",
		"mainConfigFile": "../static/javascript/main.js",
		"dir": "../public",
		"useStrict": false,
		"keepBuildDir": true,
		"wrap": false,
		"optimizeCss": "standard",
		"findNestedDependencies": true,
		"optimize": "uglify2"
		"skipDirOptimize": false,
		"preserveLicenseComments": false,
		"removeCombined": false,
		"logLevel": 0,
		"cjsTranslate": true,
		"generateSourceMaps": false,
		"uglify2": {
			"screw-ie8": true,
			"warnings": false,
			"mangle": true
		},
		"throwWhen": {
			"optimize": true
		},
		"modules": [
			{
				"name": "../main"
			}
		]
	}

**main.js**

    require.config({
      baseUrl: '/javascript/libs',
      enforceDefine: false,
      waitSeconds: 45,
      paths: {
        collections: '../collections',
        etc: '../etc',
        underscore: 'lodash',
        maskedInput: 'jquery.maskedinput',
        text: 'require_plugins/text',
        async: 'require_plugins/async',
        goog: 'require_plugins/goog',
        font: 'require_plugins/font',
        propertyParser: 'require_plugins/propertyParser'
      }
    });

    console.log("ready"); // logs to console    

    define(function(require) {

      pace = require("pace").start();
      $ = require('jquery');
      console.log("init"); // not logged to console

    });

**Comment by alexindigo** [comment]
If you can post your bundled (and unminified) version here, it will give us all better understanding.

**Comment by jwerre** [comment]
Here are the script tags I'm using:

This doesn't work (RequireJS 1.0.8):
    <script async="" data-main="https://public.surveyplanet.com/survey/0.0.1-alpha.19/javascript/main" src="https://public.surveyplanet.com/survey/0.0.1-alpha.19/javascript/libs/require.js"></script>

This works (RequireJS 1.0.8):
    <script async="" data-main="https://public.surveyplanet.com/survey/0.0.1-alpha.19/javascript/main" src="https://public.surveyplanet.com/survey/0.0.1-alpha.19/javascript/libs/require1.js"></script>

**Comment by alexindigo** [comment]
Tried to fetch `https://public.surveyplanet.com/survey/0.0.1-alpha.19/javascript/main` – said access denied.

Do you mind to post unminified versions so it will be readable? if it's big you can create gist. Thank you.

**Comment by jwerre** [comment]
oh... you need to add `.js` to the end. this should load:

https://public.surveyplanet.com/survey/0.0.1-alpha.19/javascript/main.js

**Comment by jwerre** [comment]
It's a pretty big file but at the very end you'll find the config and main scripts

**Comment by jrburke** [comment]
This sounds like [insertRequire](https://github.com/jrburke/r.js/blob/1925a7969a3ff60f66c5a742764c20baa287268f/build/example.build.js#L420) needs to be set for the module ID that is used for the define() call in main.js. The 2.x releases do not auto-execute define()'d modules, where 1.0 did.

Fairly sure this is the issue, so closing, but feel free to continue discussion here.

**Comment by jwerre** [comment]
Thanks @jrburke. Just wanted to mention that it only worked inside the modules array

	"modules": [
		{
			"name": "../main",
			"insertRequire": ['../main']
		}
	]
	"insertRequire": ['../main'] // << doesn't work here
