### ISSUE TITLE
npm install requirejs failes with Error: 0-byte tarball

### ISSUE THREAD

**Issue by marcofranssen** [jrburke/r.js#873]
Also reported the issue at npm repo. First time I experience this with a package. Would you be able to fix this at you side? Is the package just corrupt? In that case it means no-one will be able to install it via npm install.

https://github.com/npm/npm/issues/10476

**Comment by jrburke** [comment]
I just tried with a setup using node 0.10.36 and npm 2.12.1, and I am able to get the package. 

I suspect it could be a temporary network issue with npm or perhaps an issue specific to that computer's setup. Unfortunately I am not good with debugging npm issues. It could be worth trying again a bit later to see if it was a temporary network issue.

Going to close as this seems to work for me, but feel free to continue conversation here and we can reopen as needed.

**Comment by marcofranssen** [comment]
I figured it is only the release from yesterday. The release earlier
(2.1.20) does work. The release 2.1.21 is broken.

2015-11-19 16:39 GMT+01:00 James Burke <notifications@github.com>:

**Comment by jrburke** [comment]
Hmm. 2.1.21 is what I installed. When I look at `npm info requirejs` it lists this file for the tarball:
http://registry.npmjs.org/requirejs/-/requirejs-2.1.21.tgz

Do you see the same? Can you download that file manually?
