### ISSUE TITLE
TypeError intersected by require.js

### ISSUE THREAD

**Issue by epartipilo** [jrburke/r.js#877]
When changing requirejs version from 2.1.20 to 2.1.21 the console.error changes and doesn't show at first view the file and line throwing it. 
![2 1 20-console error](https://cloud.githubusercontent.com/assets/4688744/12017521/fb73e046-ad57-11e5-8b80-3cd6f85c71ff.png)
![2 1 21-console error](https://cloud.githubusercontent.com/assets/4688744/12017522/fb75bff6-ad57-11e5-9cd8-f450ae07d599.png)

**Comment by jrburke** [comment]
I am going to track this in the requirejs repo as jrburke/requirejs#1477 since the fix will be in that repo, so closing in favor of that other ticket.
