### ISSUE TITLE
r.js exits with error code 3 when launching though Rhino

### ISSUE THREAD

**Issue by gfinocchiaro** [jrburke/r.js#889]
Hello,

after cloning the project, building the r.js file and running the following commands from the root (on a Windows machine), jvm process exits with a error code 3.

```sh
>java -cp lib\rhino\js.jar;lib\closure\compiler.jar org.mozilla.javascript.tools.shell.Main r.js
>echo %errorLevel%
3
```
The same on a Linux machine:
```sh
>java -cp lib/rhino/js.jar:lib/closure/compiler.jar org.mozilla.javascript.tools.shell.Main r.js
>echo $?
3
```
What is wrong?

Bye
Gianluca

**Comment by jrburke** [comment]
The opt level change in #888 also seemed to fix this error:

https://github.com/jrburke/r.js/commit/5765c576cd96c825cf0902333e61f21564eba4a9

**Comment by mamoit** [comment]
@jrburke This should be changed in the examples presented in the `README`.
